# Generated by Django 4.0.1 on 2022-01-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
